# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'help.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import webbrowser

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormHelp(object):
    def setupUi(self, FormHelp):
        FormHelp.setObjectName("FormHelp")
        FormHelp.resize(933, 273)
        font = QtGui.QFont()
        font.setPointSize(10)
        FormHelp.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("USA-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FormHelp.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(FormHelp)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(FormHelp)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        #self.textBrowser.setSource(QtCore.QUrl.fromLocalFile("CommStatX-help.html"))

        self.open_webbrowser()

        self.retranslateUi(FormHelp)
        QtCore.QMetaObject.connectSlotsByName(FormHelp)

    def retranslateUi(self, FormHelp):
        _translate = QtCore.QCoreApplication.translate
        FormHelp.setWindowTitle(_translate("FormHelp", "CommStat Help"))

    def open_webbrowser(self):
        webbrowser.open('CommStatX-help.html')

    #btn.clicked.connect(open_webbrowser)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormHelp = QtWidgets.QWidget()
    ui = Ui_FormHelp()
    ui.setupUi(FormHelp)
    FormHelp.show()
    sys.exit(app.exec_())
